#!/usr/bin/env php
<?php declare(strict_types=1);

use App\Kernel;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\DependencyInjection\Loader\PhpFileLoader;

if (\in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) === false) {
    echo \PHP_EOL . 'php-dry may only be invoked from a command line, got "' . \PHP_SAPI . '"' . \PHP_EOL;

    exit(1);
}

(static function (): void {
    if (\file_exists($autoload = __DIR__ . '/../../autoload.php')) {
        // Is installed via Composer
        include_once $autoload;

        return;
    }

    if (\file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
        // Is installed locally
        include_once $autoload;

        return;
    }

    \fwrite(
        \STDERR,
        <<<'ERROR'
You need to set up the project dependencies using Composer:
    $ composer install
See https://getcomposer.org/.
ERROR
    );

    throw new RuntimeException('Unable to find the Composer autoloader.');
})();

// Project (third-party) autoloading
(static function (): void {
    if (\file_exists($autoload = getcwd() . '/vendor/autoload.php')) {
        include_once $autoload;
    }
})();

$kernel = new Kernel('prod', false);
$kernel->boot();

$container = $kernel->getContainer();
/** @var \App\Application $app */
$app = $container->get(\App\Application::class);

$app->setDefaultCommand('php-dry:check', true);

$app->run();
